name: Manual Build

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Choose Target
        default: 'all'
        options:
        - 'all'
        - 'esp32'
        - 'esp32s2'
        - 'esp32s3'
        - 'esp32c2'
        - 'esp32c3'
        - 'esp32c6'
        - 'esp32h2'
        - 'esp32p4'
      log_level:
        type: choice
        description: Choose Log Level
        default: 'default'
        options:
        - 'default'
        - 'none'
        - 'verbose'
        - 'debug'
        - 'info'
        - 'warning'
        - 'error'
      latest-builder:
        description: 'Update esp32-arduino-lib-builder'
        type: boolean
        default: true 

permissions:
  contents: write

jobs:
  run:
    name: Build ${{ github.ref_name }} SDK For ${{ github.event.inputs.target }} as ${{ github.event.inputs.log_level }}
    runs-on: ubuntu-latest

    env:
      VERSION_BASE: 3.3.x
      VERSION_TAG: 3.3.x.${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Apply Changes
        shell: bash
        env:
          GITHUB_UPDATE_BUILDER: ${{ github.event.inputs.latest-builder }}
        run: bash ./changes.sh

      - name: Install dependencies
        run: bash ./original/tools/prepare-ci.sh     

      - name: Build
        shell: bash
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          export TARGET_TYPE=${{ github.event.inputs.target }}
          export LOG_LEVEL=${{ github.event.inputs.log_level }}
          echo "Building for $TARGET_TYPE (log_level: $LOG_LEVEL)"
          cd original
          bash ./build.sh -e -t $TARGET_TYPE -D $LOG_LEVEL
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.run_number }} ${{ env.VERSION_BASE }} ${{ github.event.inputs.target }} (log_level: ${{ github.event.inputs.log_level }})"
          tag_name: ${{ env.VERSION_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./dist/*

      - name: Determine versions
        id: ver
        run: |
          TAG="${{ env.VERSION_TAG }}"
          MAJOR="${TAG%%.*}"
          MINOR="$(echo "$TAG" | cut -d '.' -f2)"
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT

      - name: Define release aliases
        id: aliases
        run: |
          echo "aliases=Latest ${{ steps.ver.outputs.major }}.Latest ${{ steps.ver.outputs.major }}.${{ steps.ver.outputs.minor }}.Latest" >> $GITHUB_OUTPUT

      - name: Ensure release aliases
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          for tag in ${{ steps.aliases.outputs.aliases }}; do
            echo "Checking if release with tag '$tag' exists..."
            if gh release view "$tag" >/dev/null 2>&1; then
              echo "✅ Release $tag exists — updating..."
              gh release upload "$tag" ./dist/* --clobber
            else
              echo "➕ Release $tag does not exist — creating..."
              gh release create "$tag" ./dist/* --title "$tag" --notes "Auto-created alias for $tag"
            fi
          done